const $ = (q)=>document.querySelector(q);
const canvas=$('#canvas'), svg=$('#svg'), logBox=$('#log'), detail=$('#detail');
let state={day:1,slot:0,chars:[],rels:[],logs:[]};
let selected=[]; let drag=null, ox=0, oy=0; let timer=null;
const slots=['아침','점심','방과후','저녁','밤'];
const moodList=['평온','기쁨','설렘','긴장','짜증','불안','감동','피곤','의심','외로움'];
const relColors={친구:'#10b981',소꿉친구:'#14b8a6',라이벌:'#f59e0b',가족:'#3b82f6',연인:'#ec4899',짝사랑:'#f472b6','스승/제자':'#6366f1',적대:'#ef4444','비밀 관계':'#6b7280'};
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function clamp(n,min=0,max=100){return Math.max(min,Math.min(max,n))}
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function save(){localStorage.setItem('oc-world-v2',JSON.stringify(state))}
function load(){try{const s=localStorage.getItem('oc-world-v2');if(s)state=JSON.parse(s)}catch(e){} render()}
function addLog(text,type='story'){const now=`${state.day}일차 ${slots[state.slot]}`;state.logs.unshift({time:now,text,type});state.logs=state.logs.slice(0,200);save();renderLogs()}
function renderLogs(){logBox.innerHTML='';state.logs.forEach(l=>{const d=document.createElement('div');d.className='logitem';d.innerHTML=`<div class="t">${l.time}</div><div>${esc(l.text)}</div>`;logBox.appendChild(d)})}
function esc(s=''){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
$('#btnAdd').onclick=()=>{const name=$('#name').value.trim(); if(!name)return alert('이름을 입력하세요.'); const file=$('#photo').files[0]; if(file){const r=new FileReader(); r.onload=e=>createChar(e.target.result); r.readAsDataURL(file)} else createChar('')};
function createChar(photo){const c={id:uid(),name:$('#name').value.trim(),age:$('#age').value.trim(),trait:$('#trait').value.trim(),like:$('#like').value.trim(),dislike:$('#dislike').value.trim(),catchphrase:$('#catchphrase').value.trim(),bio:$('#bio').value.trim(),photo,mood:'평온',energy:70,stress:20,charm:50+Math.floor(Math.random()*30),logic:40+Math.floor(Math.random()*35),empathy:45+Math.floor(Math.random()*35),x:80+Math.random()*420,y:80+Math.random()*300};state.chars.push(c);['name','age','trait','like','dislike','catchphrase','bio','photo'].forEach(id=>$('#'+id).value='');addLog(`${c.name}이(가) 세계에 등장했다.`);render();save()}
$('#btnRel').onclick=()=>{let a=$('#charA').value,b=$('#charB').value;if(selected.length===2){a=selected[0];b=selected[1]}if(!a||!b||a===b)return alert('서로 다른 캐릭터 2명을 선택하세요.');const type=$('#relType').value;state.rels.push({id:uid(),from:a,to:b,type,memo:$('#relMemo').value.trim(),affection:initAff(type),trust:initTrust(type),tension:initTen(type)});selected=[];$('#relMemo').value='';addLog(`${nameOf(a)}와(과) ${nameOf(b)} 사이에 '${type}' 관계가 생겼다.`);render();save()};
function initAff(t){return ({친구:65,소꿉친구:75,가족:70,연인:82,짝사랑:68,'스승/제자':55,라이벌:35,적대:10,'비밀 관계':50}[t]??50)}
function initTrust(t){return ({친구:60,소꿉친구:70,가족:65,연인:75,짝사랑:40,'스승/제자':60,라이벌:30,적대:10,'비밀 관계':35}[t]??50)}
function initTen(t){return ({친구:15,소꿉친구:10,가족:25,연인:18,짝사랑:45,'스승/제자':20,라이벌:60,적대:85,'비밀 관계':55}[t]??30)}
function nameOf(id){return state.chars.find(c=>c.id===id)?.name||'???'}
function char(id){return state.chars.find(c=>c.id===id)}
function render(){ $('#day').textContent=state.day; $('#timeSlot').textContent=slots[state.slot]; updateSelects(); canvas.querySelectorAll('.card').forEach(e=>e.remove()); svg.innerHTML=''; drawRels(); state.chars.forEach(drawCard); renderLogs(); renderDetail()}
function updateSelects(){['charA','charB'].forEach(id=>{const sel=$('#'+id),v=sel.value;sel.innerHTML='<option value="">캐릭터 선택</option>'+state.chars.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');sel.value=v})}
function drawRels(){const groups={};state.rels.forEach(r=>{const key=[r.from,r.to].sort().join('|');(groups[key]??=[]).push(r)});Object.values(groups).forEach(group=>group.forEach((r,i)=>drawRel(r,i-(group.length-1)/2)))}
function drawRel(r,offset){const a=char(r.from),b=char(r.to);if(!a||!b)return;const x1=a.x+85,y1=a.y+96,x2=b.x+85,y2=b.y+96;const mx=(x1+x2)/2,my=(y1+y2)/2;const dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy)||1;const nx=-dy/len,ny=dx/len;const curve=offset*42;const cx=mx+nx*curve,cy=my+ny*curve;const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',`M ${x1} ${y1} Q ${cx} ${cy} ${x2} ${y2}`);path.setAttribute('fill','none');path.setAttribute('stroke',relColors[r.type]||'#7c3aed');path.setAttribute('stroke-width','3');svg.appendChild(path);const text=document.createElementNS('http://www.w3.org/2000/svg','text');text.setAttribute('x',cx);text.setAttribute('y',cy-8);text.setAttribute('text-anchor','middle');text.setAttribute('class','rel-label');text.textContent=`${r.type} ♥${r.affection}`;svg.appendChild(text)}
function drawCard(c){const tpl=$('#cardTpl').content.cloneNode(true);const el=tpl.querySelector('.card');el.dataset.id=c.id;el.style.left=c.x+'px';el.style.top=c.y+'px';if(selected.includes(c.id))el.classList.add('selected');tpl.querySelector('.avatar').innerHTML=c.photo?`<img src="${c.photo}">`:'사진 없음';tpl.querySelector('h3').textContent=c.name;tpl.querySelector('.sub').textContent=[c.age,c.trait].filter(Boolean).join(' · ')||'설정 없음';tpl.querySelector('.mood').textContent=`기분: ${c.mood}`;tpl.querySelector('.bars').innerHTML=bar('활력',c.energy)+bar('스트레스',c.stress)+bar('공감',c.empathy);tpl.querySelector('.x').onclick=(e)=>{e.stopPropagation();if(confirm(`${c.name} 삭제?`)){state.chars=state.chars.filter(x=>x.id!==c.id);state.rels=state.rels.filter(r=>r.from!==c.id&&r.to!==c.id);selected=selected.filter(id=>id!==c.id);addLog(`${c.name}이(가) 세계에서 사라졌다.`);render();save()}};el.onclick=e=>{e.stopPropagation();toggle(c.id)};el.onmousedown=e=>{if(e.target.className==='x')return;drag=c;ox=e.offsetX;oy=e.offsetY};canvas.appendChild(tpl)}
function bar(n,v){return `<div class="bar"><label>${n} ${v}</label><div class="track"><div class="fill" style="width:${clamp(v)}%"></div></div></div>`}
function toggle(id){selected=selected.includes(id)?selected.filter(x=>x!==id):(selected.length>=2?[selected[1],id]:[...selected,id]);render()}
document.onmousemove=e=>{if(!drag)return;const r=canvas.getBoundingClientRect();drag.x=e.clientX-r.left-ox;drag.y=e.clientY-r.top-oy;render()};document.onmouseup=()=>{if(drag)save();drag=null};canvas.onclick=()=>{selected=[];render()};
function renderDetail(){if(selected.length!==1){detail.className='detail empty';detail.textContent=selected.length===2?'두 캐릭터가 선택되었습니다. 관계를 추가할 수 있습니다.':'캐릭터를 선택하세요.';return}const c=char(selected[0]);if(!c)return;const rels=state.rels.filter(r=>r.from===c.id||r.to===c.id);detail.className='detail';detail.innerHTML=`<b>${esc(c.name)}</b><br>${esc(c.bio||'배경 없음')}<hr><div class="stat">성격: ${esc(c.trait||'-')}</div><div class="stat">좋아함: ${esc(c.like||'-')}</div><div class="stat">싫어함: ${esc(c.dislike||'-')}</div><div class="stat">말버릇: ${esc(c.catchphrase||'-')}</div><hr><div class="stat">활력 ${c.energy} · 스트레스 ${c.stress}</div><div class="stat">매력 ${c.charm} · 논리 ${c.logic} · 공감 ${c.empathy}</div><hr><b>관계</b><br>${rels.map(r=>`${esc(nameOf(r.from===c.id?r.to:r.from))}: ${r.type} / 호감 ${r.affection} / 신뢰 ${r.trust} / 긴장 ${r.tension}`).join('<br>')||'관계 없음'}`}
$('#btnTalk').onclick=()=>talk();
function talk(){if(state.rels.length<1)return alert('관계가 1개 이상 필요합니다.');const r=pick(state.rels),a=char(r.from),b=char(r.to);if(!a||!b)return;const line=makeTalk(a,b,r);applyTalkEffects(a,b,r,line.kind);addLog(line.text,'talk');render();save()}
function makeTalk(a,b,r){const cp=a.catchphrase?` "${a.catchphrase}"`:'';let arr=[];let kind='warm';switch(r.type){case'친구':case'소꿉친구':arr=[`${a.name}이(가)${cp}라며 ${b.name}에게 장난을 걸었다. ${b.name}은(는) 웃음을 참지 못했다.`,`${b.name}이(가) ${a.name}에게 고민을 털어놓았다. ${a.name}은(는) 끝까지 들어주었다.`];kind='warm';break;case'연인':case'짝사랑':arr=[`${a.name}이(가) ${b.name}을(를) 보고 잠시 말을 잃었다. 공기가 조금 달라졌다.`,`${b.name}이(가) ${a.name}에게 작은 칭찬을 했다. ${a.name}의 표정이 부드러워졌다.`];kind='romance';break;case'라이벌':arr=[`${a.name}와(과) ${b.name}이(가) 누가 더 나은지 신경전을 벌였다.`,`${b.name}이(가) ${a.name}의 실력을 인정했지만, 절대 지고 싶지는 않아 했다.`];kind='rival';break;case'적대':arr=[`${a.name}이(가) ${b.name}을(를) 차갑게 바라보았다. 말 한마디가 날카로웠다.`,`${b.name}이(가) ${a.name}의 약점을 건드렸다. 분위기가 험악해졌다.`];kind='bad';break;case'비밀 관계':arr=[`${a.name}와(과) ${b.name}이(가) 아무도 모르게 짧은 암호 같은 대화를 나누었다.`,`${b.name}이(가) ${a.name}에게 의미심장한 눈빛을 보냈다.`];kind='secret';break;default:arr=[`${a.name}와(과) ${b.name}이(가) 조용히 이야기를 나누었다.`];}return{text:pick(arr),kind}}
function applyTalkEffects(a,b,r,kind){let da=0,dt=0,ds=0;if(kind==='warm'){da=3;dt=2;ds=-2;a.mood=b.mood='기쁨'}else if(kind==='romance'){da=4;dt=1;ds=1;a.mood=b.mood='설렘'}else if(kind==='rival'){da=Math.random()<.5?1:-1;dt=0;ds=3;a.mood=b.mood='긴장'}else if(kind==='bad'){da=-4;dt=-2;ds=5;a.mood='짜증';b.mood='의심'}else if(kind==='secret'){da=2;dt=Math.random()<.5?2:-1;ds=3;a.mood=b.mood='긴장'}r.affection=clamp(r.affection+da);r.trust=clamp(r.trust+dt);r.tension=clamp(r.tension+ds);[a,b].forEach(c=>{c.energy=clamp(c.energy-2);c.stress=clamp(c.stress+Math.max(0,ds))})}
$('#btnNext').onclick=nextTime;function nextTime(){state.slot++;if(state.slot>=slots.length){state.slot=0;state.day++;state.chars.forEach(c=>{c.energy=clamp(c.energy+20);c.stress=clamp(c.stress-10);c.mood=pick(['평온','기쁨','피곤'])});addLog('새로운 하루가 시작되었다.')}else addLog(`${slots[state.slot]} 시간이 되었다.`); if(Math.random()<.45)randomEvent(false);render();save()}
$('#btnEvent').onclick=()=>randomEvent(true);function randomEvent(force){if(state.chars.length<1)return alert('캐릭터가 필요합니다.');const c=pick(state.chars);const events=[()=>{c.energy=clamp(c.energy-15);c.stress=clamp(c.stress+10);c.mood='피곤';return `${c.name}이(가) 밤늦게까지 생각에 잠겨 피곤해졌다.`},()=>{c.stress=clamp(c.stress-12);c.mood='기쁨';return `${c.name}이(가) 좋아하는 ${c.like||'무언가'}을(를) 발견하고 기분이 좋아졌다.`},()=>{c.stress=clamp(c.stress+15);c.mood='불안';return `${c.name}이(가) 싫어하는 ${c.dislike||'상황'} 때문에 불안해졌다.`},()=>{if(state.rels.length){const r=pick(state.rels);r.affection=clamp(r.affection+5);return `${nameOf(r.from)}와(과) ${nameOf(r.to)} 사이에 작은 오해가 풀렸다.`}return `${c.name}이(가) 조용한 하루를 보냈다.`}];addLog(pick(events)());render();save()}
$('#btnAuto').onclick=()=>{if(timer){clearInterval(timer);timer=null;$('#btnAuto').textContent='자동 진행 시작'}else{timer=setInterval(()=>{Math.random()<.65?talk():nextTime()},2800);$('#btnAuto').textContent='자동 진행 정지'}};
$('#btnExport').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='oc-world-save.json';a.click();URL.revokeObjectURL(a.href)};
$('#importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();render();alert('불러오기 완료')}catch(err){alert('잘못된 파일입니다.')}};r.readAsText(f)};
$('#btnReset').onclick=()=>{if(confirm('정말 모든 데이터를 삭제할까요?')){localStorage.removeItem('oc-world-v2');state={day:1,slot:0,chars:[],rels:[],logs:[]};selected=[];render()}};
load();
