let editingId=null,autoTimer=null,dragging=null,dx=0,dy=0;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active');renderAll();});
$('#tickBtn').onclick=tick; $('#eventBtn').onclick=bigEvent; $('#autoBtn').onclick=()=>{if(autoTimer){clearInterval(autoTimer);autoTimer=null;$('#autoBtn').textContent='자동 진행 시작'}else{autoTimer=setInterval(tick,2500);$('#autoBtn').textContent='자동 진행 정지'}};
$('#editWorldBtn').onclick=()=>{$('#worldNameInput').value=state.world.name;$('#worldDescInput').value=state.world.desc;$('#worldDialog').showModal()};
$('#saveWorldBtn').onclick=e=>{e.preventDefault();state.world.name=$('#worldNameInput').value||'나의 자캐 세계관';state.world.desc=$('#worldDescInput').value||'';saveState();$('#worldDialog').close();renderAll();};
$('#newCharacterBtn').onclick=()=>openCharDialog();
function openCharDialog(c=null){editingId=c?.id||null;$('#charDialogTitle').textContent=c?'캐릭터 수정':'캐릭터 추가';$('#nameInput').value=c?.name||'';$('#roleInput').value=c?.role||'';$('#bioInput').value=c?.bio||'';$('#charmInput').value=c?.stats?.charm??50;$('#mindInput').value=c?.stats?.mind??50;$('#braveInput').value=c?.stats?.brave??50;$('#socialInput').value=c?.stats?.social??50;$('#imageInput').value='';$('#charDialog').showModal()}
$('#saveCharBtn').onclick=e=>{e.preventDefault();const file=$('#imageInput').files[0];const done=img=>{const data={name:$('#nameInput').value.trim(),role:$('#roleInput').value.trim(),bio:$('#bioInput').value.trim(),image:img,stats:{charm:+$('#charmInput').value,mind:+$('#mindInput').value,brave:+$('#braveInput').value,social:+$('#socialInput').value}};if(!data.name)return alert('이름을 입력하세요.');if(editingId){const c=state.characters.find(x=>x.id===editingId);Object.assign(c,data,{image:img||c.image});saveState();renderAll();}else makeCharacter(data);$('#charDialog').close();}; if(file){const r=new FileReader();r.onload=ev=>done(ev.target.result);r.readAsDataURL(file)}else done('')};
$('#addRelationBtn').onclick=()=>addRelation($('#fromSelect').value,$('#toSelect').value,$('#typeSelect').value);
$('#clearLogsBtn').onclick=()=>{if(confirm('기록을 지울까요?')){state.logs=[];saveState();renderAll();}};
$('#exportStoryBtn').onclick=()=>downloadFile('oc-story.txt',state.logs.slice().reverse().map(l=>`[Day ${l.day} ${l.phase}] ${l.type}: ${l.text}`).join('\n'),'text/plain');
$('#exportBtn').onclick=()=>downloadFile('oc-world-backup.json',JSON.stringify(state,null,2));
$('#importInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=ev=>{try{state=JSON.parse(ev.target.result);saveState();renderAll();alert('가져오기 완료')}catch(err){alert('파일을 읽을 수 없습니다.')}};r.readAsText(f)};
$('#resetBtn').onclick=()=>{if(confirm('정말 전체 초기화할까요?')){localStorage.removeItem(STORE_KEY);state=defaultState();renderAll();}};
function renderAll(){renderWorld();renderCharacters();renderSelects();renderRelations();renderLogs();}
function renderWorld(){$('#worldTitle').textContent=state.world.name;$('#worldDesc').textContent=state.world.desc;$('#dayText').textContent=state.day;$('#phaseText').textContent=phases[state.phaseIndex];$('#charCount').textContent=state.characters.length;$('#relCount').textContent=state.relations.length;$('#logCount').textContent=state.logs.length;$('#recentLogs').innerHTML=state.logs.slice(0,5).map(logHtml).join('')||'<p class="muted">아직 이야기가 없습니다.</p>'}
function renderCharacters(){const el=$('#characterGrid');el.innerHTML=state.characters.map(c=>`<div class="charCard"><img class="charImg" src="${c.image||''}" onerror="this.style.display='none'"><h3>${esc(c.name)}</h3><div class="muted">${esc(c.role||'역할 없음')}</div><p>${esc(c.bio||'설명 없음')}</p><span class="tag">기분: ${c.mood}</span><span class="tag">체력: ${c.energy}</span><div class="bars">${bar('매력',c.stats.charm)}${bar('지성',c.stats.mind)}${bar('용기',c.stats.brave)}${bar('친화력',c.stats.social)}</div><button onclick="openCharDialog(state.characters.find(c=>c.id==='${c.id}'))">수정</button> <button class="danger" onclick="delChar('${c.id}')">삭제</button></div>`).join('')||'<p class="muted">캐릭터를 추가해보세요.</p>'}
window.delChar=id=>{if(!confirm('삭제할까요?'))return;state.characters=state.characters.filter(c=>c.id!==id);state.relations=state.relations.filter(r=>r.from!==id&&r.to!==id);saveState();renderAll();}
function renderSelects(){const opts=state.characters.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('#fromSelect').innerHTML=opts;$('#toSelect').innerHTML=opts;}
function renderRelations(){const canvas=$('#relationCanvas'),svg=$('#relationSvg');canvas.querySelectorAll('.node').forEach(n=>n.remove());svg.innerHTML='';const groups={};state.relations.forEach(r=>{const key=[r.from,r.to].sort().join('_');(groups[key]??=[]).push(r)});Object.values(groups).forEach(group=>group.forEach((r,i)=>drawRel(r,i,group.length)));state.characters.forEach(c=>{const n=document.createElement('div');n.className='node';n.style.left=c.x+'px';n.style.top=c.y+'px';n.innerHTML=`${c.image?`<img src="${c.image}">`:''}<b>${esc(c.name)}</b><div class="small">${c.mood} · 체력 ${c.energy}</div>`;n.onmousedown=e=>{dragging=c;dx=e.offsetX;dy=e.offsetY};canvas.appendChild(n)});$('#relationList').innerHTML=state.relations.map(r=>`<div class="relItem"><b>${nameOf(r.from)} ↔ ${nameOf(r.to)}</b><br><span class="muted">${r.type} · 호감 ${r.score} · 긴장 ${r.tension}</span><br><button onclick="delRel('${r.id}')">삭제</button></div>`).join('')||'<p class="muted">관계가 없습니다.</p>'}
window.delRel=id=>{state.relations=state.relations.filter(r=>r.id!==id);saveState();renderAll();}
function drawRel(r,index,total){const a=state.characters.find(c=>c.id===r.from),b=state.characters.find(c=>c.id===r.to);if(!a||!b)return;const x1=a.x+72,y1=a.y+55,x2=b.x+72,y2=b.y+55;const mx=(x1+x2)/2,my=(y1+y2)/2;const vx=x2-x1,vy=y2-y1,len=Math.hypot(vx,vy)||1;const offset=(index-(total-1)/2)*55;const cx=mx+(-vy/len)*offset,cy=my+(vx/len)*offset;const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',`M ${x1} ${y1} Q ${cx} ${cy} ${x2} ${y2}`);path.setAttribute('class','relLine');path.setAttribute('stroke',colorOf(r.type));$('#relationSvg').appendChild(path);const text=document.createElementNS('http://www.w3.org/2000/svg','text');text.setAttribute('x',cx);text.setAttribute('y',cy-6);text.setAttribute('text-anchor','middle');text.setAttribute('class','relText');text.textContent=`${r.type} ${r.score}`;$('#relationSvg').appendChild(text)}
function colorOf(t){return{친구:'#10b981',라이벌:'#f59e0b',가족:'#3b82f6',연인:'#ec4899','스승/제자':'#6366f1',적대:'#ef4444','비밀 관계':'#9ca3af',동료:'#14b8a6'}[t]||'#a78bfa'}
document.addEventListener('mousemove',e=>{if(!dragging)return;const rect=$('#relationCanvas').getBoundingClientRect();dragging.x=e.clientX-rect.left-dx;dragging.y=e.clientY-rect.top-dy;renderRelations();});document.addEventListener('mouseup',()=>{if(dragging){saveState()}dragging=null});
function renderLogs(){$('#storyLog').innerHTML=state.logs.map(logHtml).join('')||'<p class="muted">아직 기록이 없습니다.</p>'}
function logHtml(l){return`<div class="logItem"><div class="logTime">Day ${l.day} · ${l.phase} · ${l.type} · ${l.time}</div>${esc(l.text)}</div>`}
function bar(name,v){return`<div class="muted">${name} ${v}</div><div class="bar"><span style="width:${v}%"></span></div>`}
function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
renderAll();
